name: Create Release

on:
  release:
    types: [created]

env:
    PACKAGE_ID: "Mtd.Core"
    COPYRIGHT: "Champaign-Urbana Mass Transit District"
    LICENSE: "Apache-2.0"
    ICON: "icon.png"
    README: "readme.md"
    REPO: "git@github.com:CUMTD/Mtd.Core.git"
    DESCRIPTION: "Core code shared by most MTD projects."
    OUTPUT: "nupkgs"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/cumtd/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release Mtd.Core.sln
      - name: Create the package
        run: dotnet pack Mtd.Core.sln -p:PackageVersion="${{ env.GITHUB_REF_NAME }}" -p:PackageId="$PACKAGE_ID" -p:Copyright="$COPYRIGHT" -p:PackageRequireLicenseAcceptance=false -p:PackageLicenseExpression="$LICENSE" -p:PackageIcon="$ICON" -p:PackageReadmeFile="$README" -p:RepositoryUrl="$REPO" -p:RepositoryType=git -p:Description="$DESCRIPTION" --include-source --no-build --no-restore --configuration Release --output $OUTPUT
      - name: Publish the package to GPR
        run: dotnet nuget push $OUTPUT/*.nupkg